### ISSUE TITLE
Segmentation Violation in vs_write_packet

### ISSUE THREAD

**Issue by dantheman2865** [horgh/videostreamer#6]
Hello,

I've found an issue when I run multiple versions of the process at once:
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f71c7347849]

runtime stack:
runtime.throw(0x6f0eda, 0x2a)
        /usr/local/go/src/runtime/panic.go:605 +0x95
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:351 +0x2b8

goroutine 70 [syscall, locked to thread]:
runtime.cgocall(0x643a10, 0xc420479f40, 0xc420404178)
        /usr/local/go/src/runtime/cgocall.go:132 +0xe4 fp=0xc420479f10 sp=0xc420479ed0 pc=0x4040f4
main._Cfunc_vs_write_packet(0x7f71a0000930, 0x7f7164015980, 0x7f7160000b20, 0x0, 0x0)
        github.com/horgh/videostreamer/_obj/_cgo_gotypes.go:1161 +0x4d fp=0xc420479f40 sp=0xc420479f10 pc=0x63c83d
main.packetWriter.func1(0x7f71a0000930, 0x7f7164015980, 0x7f7160000b20, 0x0, 0x1)
        /home/swiftlet/work/src/github.com/horgh/videostreamer/videostreamer.go:343 +0xeb fp=0xc420479f78 sp=0xc420479f40 pc=0x63fb4b
main.packetWriter(0xc42000c020, 0x7f71a0000930, 0x0)
        /home/swiftlet/work/src/github.com/horgh/videostreamer/videostreamer.go:343 +0xd8 fp=0xc420479fc8 sp=0xc420479f78 pc=0x63e6a8
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420479fd0 sp=0xc420479fc8 pc=0x45a301
created by main.writePacketToClients
        /home/swiftlet/work/src/github.com/horgh/videostreamer/videostreamer.go:307 +0x46f

goroutine 1 [IO wait, 6 minutes]:
internal/poll.runtime_pollWait(0x7f71c993cf70, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420114018, 0x72, 0xc420067a00, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420114018, 0xffffffffffffff00, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc420114000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:335 +0x1e2
net.(*netFD).accept(0xc420114000, 0x413f99, 0xc420358080, 0x686f20)
        /usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc42000e040, 0x686f20, 0xc420067c60, 0x4029c7)
        /usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).AcceptTCP(0xc42000e040, 0xc420067ca8, 0xc420067cb0, 0xc420067ca0)
        /usr/local/go/src/net/tcpsock.go:234 +0x49
net/http.tcpKeepAliveListener.Accept(0xc42000e040, 0x6f8e58, 0xc420358000, 0xa395a0, 0xc420082e70)
        /usr/local/go/src/net/http/server.go:3120 +0x2f
net/http.(*Server).Serve(0xc42008ec30, 0xa390e0, 0xc42000e040, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2695 +0x1b2
net/http.(*Server).ListenAndServe(0xc42008ec30, 0x27, 0xc420067e50)
        /usr/local/go/src/net/http/server.go:2636 +0xa9
main.main()
        /home/swiftlet/work/src/github.com/horgh/videostreamer/videostreamer.go:95 +0x601

goroutine 5 [chan receive]:
main.encoder(0x7fff79ef273f, 0x4, 0x7fff79ef2756, 0x3d, 0x0, 0xc420080120)
        /home/swiftlet/work/src/github.com/horgh/videostreamer/videostreamer.go:147 +0xcd
created by main.main
        /home/swiftlet/work/src/github.com/horgh/videostreamer/videostreamer.go:64 +0x193

goroutine 16 [runnable]:
syscall.Syscall(0x0, 0xd, 0xc420412000, 0x400, 0x400, 0x400, 0x0)
        /usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0xd, 0xc420412000, 0x400, 0x400, 0xc4204cda01, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:756 +0x55
syscall.Read(0xd, 0xc420412000, 0x400, 0x400, 0x3f, 0xc4204cdb08, 0x412e07)
        /usr/local/go/src/syscall/syscall_unix.go:162 +0x49
internal/poll.(*FD).Read(0xc420564000, 0xc420412000, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:122 +0x125
os.(*File).read(0xc42053e018, 0xc420412000, 0x400, 0x400, 0xc420126140, 0x0, 0x0)
        /usr/local/go/src/os/file_unix.go:216 +0x4e
os.(*File).Read(0xc42053e018, 0xc420412000, 0x400, 0x400, 0x400, 0x400, 0x0)
        /usr/local/go/src/os/file.go:103 +0x6d
main.HTTPHandler.streamRequest(0x6f2f00, 0xc420080120, 0xa38fa0, 0xc420552000, 0xc42056c200)
        /home/swiftlet/work/src/github.com/horgh/videostreamer/videostreamer.go:416 +0x2a3
main.HTTPHandler.ServeHTTP(0xc4204cdc00, 0xc420080120, 0xa38fa0, 0xc420552000, 0xc42056c200)
        /home/swiftlet/work/src/github.com/horgh/videostreamer/videostreamer.go:379 +0x2a5
main.(*HTTPHandler).ServeHTTP(0xc420058b00, 0xa38fa0, 0xc420552000, 0xc42056c200)
        <autogenerated>:1 +0x62
net/http.serverHandler.ServeHTTP(0xc42008ec30, 0xa38fa0, 0xc420552000, 0xc42056c200)
        /usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc420358000, 0xa394e0, 0xc4201260c0)
        /usr/local/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2720 +0x288

goroutine 38 [IO wait, 6 minutes]:
internal/poll.runtime_pollWait(0x7f71c993c970, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420354018, 0x72, 0xffffffffffffff00, 0xa366e0, 0xa33280)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420354018, 0xc420356000, 0x1, 0x1)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420354000, 0xc4203560d1, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:126 +0x18a
net.(*netFD).Read(0xc420354000, 0xc4203560d1, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc42000ea30, 0xc4203560d1, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:176 +0x6d
net/http.(*connReader).backgroundRead(0xc4203560c0)
        /usr/local/go/src/net/http/server.go:660 +0x62
created by net/http.(*connReader).startBackgroundRead
        /usr/local/go/src/net/http/server.go:656 +0xd8

```
As far as I can tell, one instance will run all day without a problem, but once I add another simultaneous process it craps out after a few minutes.

I'll run in verbose mode and find if that yields more information.

**Comment by dantheman2865** [comment]
From the logs it looks like the client disconnects (in this instance) prior to the SEGV:
```
in: pts:45986310 pts_time:510.959 dts:45986310 dts_time:510.959 duration:3000 duration_time:0.0333333 stream_index:0
out: pts:45986310 pts_time:510.959 dts:45986310 dts_time:510.959 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:45989280 pts_time:510.992 dts:45989280 dts_time:510.992 duration:3000 duration_time:0.0333333 stream_index:0
out: pts:45989280 pts_time:510.992 dts:45989280 dts_time:510.992 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:45992250 pts_time:511.025 dts:45992250 dts_time:511.025 duration:3000 duration_time:0.0333333 stream_index:0
out: pts:45992250 pts_time:511.025 dts:45992250 dts_time:511.025 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:45995310 pts_time:511.059 dts:45995310 dts_time:511.059 duration:3000 duration_time:0.0333333 stream_index:0
out: pts:45995310 pts_time:511.059 dts:45995310 dts_time:511.059 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:45998280 pts_time:511.092 dts:45998280 dts_time:511.092 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46001340 pts_time:511.126 dts:46001340 dts_time:511.126 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46004310 pts_time:511.159 dts:46004310 dts_time:511.159 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46007280 pts_time:511.192 dts:46007280 dts_time:511.192 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46010340 pts_time:511.226 dts:46010340 dts_time:511.226 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46013310 pts_time:511.259 dts:46013310 dts_time:511.259 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46016370 pts_time:511.293 dts:46016370 dts_time:511.293 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46019340 pts_time:511.326 dts:46019340 dts_time:511.326 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46022310 pts_time:511.359 dts:46022310 dts_time:511.359 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46025370 pts_time:511.393 dts:46025370 dts_time:511.393 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46028340 pts_time:511.426 dts:46028340 dts_time:511.426 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46031400 pts_time:511.46 dts:46031400 dts_time:511.46 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46034370 pts_time:511.493 dts:46034370 dts_time:511.493 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46037340 pts_time:511.526 dts:46037340 dts_time:511.526 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46040400 pts_time:511.56 dts:46040400 dts_time:511.56 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46043370 pts_time:511.593 dts:46043370 dts_time:511.593 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46046430 pts_time:511.627 dts:46046430 dts_time:511.627 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46049400 pts_time:511.66 dts:46049400 dts_time:511.66 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46052370 pts_time:511.693 dts:46052370 dts_time:511.693 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46055430 pts_time:511.727 dts:46055430 dts_time:511.727 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46058400 pts_time:511.76 dts:46058400 dts_time:511.76 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46061460 pts_time:511.794 dts:46061460 dts_time:511.794 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46064430 pts_time:511.827 dts:46064430 dts_time:511.827 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46067400 pts_time:511.86 dts:46067400 dts_time:511.86 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46070460 pts_time:511.894 dts:46070460 dts_time:511.894 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46073430 pts_time:511.927 dts:46073430 dts_time:511.927 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46076400 pts_time:511.96 dts:46076400 dts_time:511.96 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46079460 pts_time:511.994 dts:46079460 dts_time:511.994 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46082430 pts_time:512.027 dts:46082430 dts_time:512.027 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46085490 pts_time:512.061 dts:46085490 dts_time:512.061 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46088460 pts_time:512.094 dts:46088460 dts_time:512.094 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46091430 pts_time:512.127 dts:46091430 dts_time:512.127 duration:3000 duration_time:0.0333333 stream_index:0
in: pts:46094490 pts_time:512.161 dts:46094490 dts_time:512.161 duration:3000 duration_time:0.0333333 stream_index:0
2018/01/23 15:14:00 Client too slow
unable to write trailer
2018/01/23 15:14:00 encoder: 0 clients
2018/01/23 15:14:00 encoder: Closed input
2018/01/23 15:14:00 encoder: Waiting for clients...
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x7fad92230736]

runtime stack:
...
```

**Comment by horgh** [comment]
Yikes!

It only happens when running multiple videostreamers? Are they on the same host? Or multiple clients? Are there steps you could tell me to reproduce it?

I pushed a branch `horgh/races` that may fix it. The line that looks most suspicious from the goroutine dump is line 343 in `packetWriter()`. Reviewing it, I think there is a race to close the client's output as well as the input. In the commit I use mutexes to protect them. However even without this commit, Go's race detector does not complain, so I'm not sure this is the problem.

**Comment by dantheman2865** [comment]
Thanks @horgh, I'll check out the branch tomorrow. To reproduce:
1. Build videostreamer with go 1.9.2 on Ubuntu 16.04 with FFMpeg installed from ppa:jonathonf/ffmpeg-3
2. Start one instance of videostreamer streaming rtsp onto port 9000
3. Start a second instance of videostreamer streaming rtsp into port 9001
4. Open both streams in browser windows, but don't view them directly (e.g. switch to other tabs). This step may be the reason that the client connection is closed; it's not important to my application, but the way I was testing today.
5. Wait ~5 minutes until one instance Seg Faults (it could be either instance as far as I know).

**Comment by horgh** [comment]
I tried this, though with ffmpeg from Debian's stretch repo. It didn't happen unfortunately. I hope ffmpeg isn't the culprit!

Another thing we could look at if the changes in the branch don't fix it is running videostreamer under gdb. A C stack trace may show more, and we should be able to see what contains the null we're accessing. There are some [docs](https://golang.org/doc/gdb) on using gdb with Go (I can't recall doing it before, so I don't know how useful it will be).

**Comment by dantheman2865** [comment]
Hi Will,
horgh/races doesn't seem to solve the problem. I also tried compiling on Debian 9 with their FFMPEG libraries and that didn't help either.

Maybe some insight, I noticed that the client connection closes just fine (x -> 0 clients), but the SEGV is thrown when I try to restart the connection (0 -> 1 client). Maybe there's a reference being disposed which should not be?

**Comment by horgh** [comment]
That is unfortunate!

One other thought I have is the parameter checking in PR#7 might help. If you add that, ideally to the races branch, that might fix it. I haven't had a chance to integrate the changes yet. You may not want the other changes in that PR though, I haven't looked them over yet.

**Comment by horgh** [comment]
Hi Dan

I've done more debugging, with a lot of help from @rbisewski from #7 who has been able to reproduce segfaults. With the latest commit I pushed however we cannot.

If it still happens, could you try building with clang's address sanitizer and see what it complains about?

You should be able to do it this way:

`CC=clang CGO_CFLAGS="-g -fsanitize=address" CGO_LDFLAGS="-fsanitize=address" go build`

Then run videostreamer as normal.

Running it under valgrind can show problems too, but valgrind also shows a bunch of false positives from Go itself. However some output showing what I think is the problem:

```
==4629== Thread 9:
==4629== Invalid read of size 1
==4629==    at 0x4E922C2: ffurl_write (in /usr/lib/libavformat.so.57.83.100)
==4629==    by 0x4E94087: avio_flush (in /usr/lib/libavformat.so.57.83.100)
==4629==    by 0x4F2D90D: ??? (in /usr/lib/libavformat.so.57.83.100)
==4629==    by 0x4F2FCEB: ??? (in /usr/lib/libavformat.so.57.83.100)
==4629==    by 0x4F30052: ??? (in /usr/lib/libavformat.so.57.83.100)
==4629==    by 0x4F4CB7A: av_write_frame (in /usr/lib/libavformat.so.57.83.100)
==4629==    by 0x6446B6: vs_write_packet (videostreamer.c:460)
==4629==    by 0x643A42: _cgo_143e9164e804_Cfunc_vs_write_packet (cgo-gcc-prolog:196)
==4629==    by 0x458F6F: runtime.asmcgocall (/usr/lib/go/src/runtime/asm_amd64.s:624)
==4629==    by 0xC4204628FF: ???
==4629==    by 0x1E978D0F: ???
==4629==    by 0x456727: runtime.goready.func1 (/usr/lib/go/src/runtime/proc.go:298)
==4629==  Address 0x1b3e33c0 is 32 bytes inside a block of size 104 free'd
==4629==    at 0x4C2E10B: free (vg_replace_malloc.c:530)
==4629==    by 0x4E91965: ??? (in /usr/lib/libavformat.so.57.83.100)
==4629==    by 0x4E919C3: ffurl_close (in /usr/lib/libavformat.so.57.83.100)
==4629==    by 0x4E95848: avio_close (in /usr/lib/libavformat.so.57.83.100)
==4629==    by 0x4E9588C: avio_closep (in /usr/lib/libavformat.so.57.83.100)
==4629==    by 0x6440FF: vs_destroy_output (videostreamer.c:259)
==4629==    by 0x458F6F: runtime.asmcgocall (/usr/lib/go/src/runtime/asm_amd64.s:624)
==4629==    by 0x456200: runtime.newdefer.func1 (/usr/lib/go/src/runtime/panic.go:206)
==4629==    by 0x1A092ACF: ???
==4629==    by 0x1A0929CE: ???
==4629==    by 0x1A0929CD: ???
==4629==    by 0xC420462EFF: ???
==4629==  Block was alloc'd at
==4629==    at 0x4C2F246: memalign (vg_replace_malloc.c:857)
==4629==    by 0x4C2F361: posix_memalign (vg_replace_malloc.c:1020)
==4629==    by 0x6B9AA2B: av_malloc (in /usr/lib/libavutil.so.55.78.100)
==4629==    by 0x6B9ABF9: av_mallocz (in /usr/lib/libavutil.so.55.78.100)
==4629==    by 0x4E911DF: ??? (in /usr/lib/libavformat.so.57.83.100)
==4629==    by 0x4E91A0E: ??? (in /usr/lib/libavformat.so.57.83.100)
==4629==    by 0x4E95AD7: ??? (in /usr/lib/libavformat.so.57.83.100)
==4629==    by 0x4E95B3E: avio_open2 (in /usr/lib/libavformat.so.57.83.100)
==4629==    by 0x644216: vs_open_output (videostreamer.c:184)
==4629==    by 0x6439B2: _cgo_143e9164e804_Cfunc_vs_open_output (cgo-gcc-prolog:141)
==4629==    by 0x458F6F: runtime.asmcgocall (/usr/lib/go/src/runtime/asm_amd64.s:624)
==4629==    by 0x1A893D0F: ???
```

**Comment by horgh** [comment]
By the way, I've only been able to reproduce it once. It happened for me after running with many clients and then occurred when I was closing them all.

**Comment by dantheman2865** [comment]
Hi @horgh and @rbisewski, the latest push to the races branch works for me. Thanks for the fix!

**Comment by horgh** [comment]
Great to hear. Thanks for letting me know!
